---
title: "Date Summary"
output:
    html_document
---

``` {r, include=FALSE}
library(knitr)
library(ggplot2)
library(dplyr, warn.conflicts=FALSE)
library(lubridate, warn.conflicts=FALSE)
library(reshape2)
library(DT)

opts_chunk$set(fig.align='center', echo=FALSE)

pg_conf <- read.csv('rds_settings', stringsAsFactors=FALSE)

vs_db <- src_postgres(dbname='vitalsigns', host=pg_conf$host,
                      user=pg_conf$user, password=pg_conf$pass,
                      port=pg_conf$port)

hh <- tbl(vs_db, 'household') %>%
        select(country, landscape_no, eplot_no, hh_no, round, interview_date) %>% 
        data.frame
ag <- tbl(vs_db, 'agric') %>%
        select(country, landscape_no, eplot_no, hh_no, round, date_of_interview) %>% 
        data.frame
hhv <- tbl(vs_db, 'household_secV') %>%
        select(country, landscape_no, eplot_no, hh_no, round, end_date) %>% 
        data.frame
ffs <- tbl(vs_db, 'farmfieldsoils') %>%
        select(country, landscape_no, eplot_no, hh_no, round, data_collection_date) %>% 
        data.frame
ffs_l <- tbl(vs_db, 'farmfieldsoils_lab') %>%
        select(country, landscape_no, eplot_no, hh_no, round, date) %>% 
        data.frame
ffs_ypm <- tbl(vs_db, 'yields_hh') %>%
        select(country, landscape_no, eplot_no, hh_no, round, y=data_collection_date) %>% 
        data.frame
ffs_yw <- tbl(vs_db, 'yieldslab') %>%
        select(country, landscape_no, eplot_no, hh_no, round, z=analysis_date) %>% 
        data.frame
ffs_p <- tbl(vs_db, 'farmfieldsoils_processed') %>%
        select(country, landscape_no, eplot_no, hh_no, round, sample_date) %>% 
        data.frame

#Reduce(merge, c(hh, ag, hhv, ffs, ffs_l, ffs_ym, ffs_ypm, ffs_yw), all=T)

all <- Reduce(function(x,y) merge(x, y, all=T),
              list(hh, ag, ffs, hhv, ffs_l, ffs_ypm, ffs_yw, ffs_p)) %>%
          arrange(country, landscape_no, eplot_no, hh_no, round)
```



Report generated `r now(tzone='UTC')` UTC.

```{r}
DT::datatable(all %>% unique, rownames = F, colnames = c("C", "L", "E", "HH", "R", "Household", "Agric", "FFS", "SecV", "FFS Lab", "Yields", "Yields Lab", "Processed Soils"))
```
