---
title: "Eplot data collection report"
output:
    html_document:
        toc: true
---

``` {r, include=FALSE}
library(knitr)
library(ggplot2)
library(dplyr, warn.conflicts=FALSE)
library(lubridate, warn.conflicts=FALSE)

opts_chunk$set(fig.align='center', echo=FALSE)

pg_conf <- read.csv('rds_settings', stringsAsFactors=FALSE)
vs_db <- src_postgres(dbname='vitalsigns', host=pg_conf$host,
                      user=pg_conf$user, password=pg_conf$pass,
                      port=pg_conf$port)
```

Report generated `r now(tzone='UTC')` UTC.

## Number of eplots outside landscapes

``` {r, fig.align="center"}
eplot <- tbl(vs_db, 'eplot')
eplot_inls <- group_by(eplot, country, landscape_no) %>%
    filter(landscape_no == '000') %>%
    summarise(n()) %>%
    arrange(country, landscape_no) %>%
    collect() %>%
    print(n=50)
ggplot(eplot_inls) +
    geom_bar(aes(country, count, fill=country), stat='identity') +
    xlab("Landscape") + ylab("Number of eplots")
```

## Number of eplots by landscape (within landscapes)

``` {r, fig.align="center"}
eplot <- tbl(vs_db, 'eplot')
eplot_outls <- group_by(eplot, country, landscape_no) %>%
    filter(landscape_no != '000') %>%
    summarise(n()) %>%
    arrange(country, landscape_no) %>%
    collect() %>%
    print(n=50)
ggplot(eplot_outls) +
    geom_bar(aes(factor(landscape_no), count, fill=country), stat='identity') +
    facet_grid(country ~ .) +
    xlab("Landscape") + ylab("Number of eplots")
```

## Number of eplots by country

``` {r}
eplot_bycountry <- group_by(eplot, country) %>%
    summarise(n()) %>%
    collect() %>%
    print()

ggplot(eplot_bycountry) +
    geom_bar(aes(factor(country), count, fill=country), stat='identity') +
    xlab("Country") + ylab("Number of eplots")
```
