---
title: "Eplot Metadata Summary"
output: html_document
---


``` {r, include=FALSE}
library(knitr)
library(ggplot2)
library(dplyr, warn.conflicts=FALSE)
library(lubridate, warn.conflicts=FALSE)
library(reshape2)
library(DT)

opts_chunk$set(fig.align='center', echo=FALSE)

pg_conf <- read.csv('rds_settings', stringsAsFactors=FALSE)

vs_db <- src_postgres(dbname='vitalsigns', host=pg_conf$host,
                      user=pg_conf$user, password=pg_conf$pass,
                      port=pg_conf$port)

eplot <- tbl(vs_db, 'eplot') %>%
        group_by(country, landscape_no, eplot_no) %>% 
        summarise(household=n()) %>%
        data.frame
soils <- tbl(vs_db, 'eplotsoils_sample') %>%
        group_by(country, landscape_no, eplot_no) %>% 
        summarise(agric=n()) %>%
        data.frame
lab <- tbl(vs_db, 'eplotsoils_lab') %>%
        group_by(country, landscape_no, eplot_no) %>% 
        summarise(household_secV=n()) %>%
        data.frame


#Reduce(merge, c(hh, ag, hhv, ffs, ffs_l, ffs_ym, ffs_ypm, ffs_yw), all=T)

all <- Reduce(function(x,y) merge(x, y, all=T),
              list(eplot, soils, lab)) %>%
          arrange(country, landscape_no, eplot_no)

all[is.na(all)] <- 0
```

##A table of entries for eplots in the database across all of the eplot protocols, for targeting duplicates and missing records

Report generated `r now(tzone='UTC')` UTC.

```{r}
DT::datatable(all, rownames = F, colnames = c("CTY", "Landscape", "Eplot Number", "Eplot Biomass", "Eplot Soils", "Soils Lab"))
```
