---
title: "Household survey data collection report"
output:
    html_document:
        toc: true
---

``` {r, echo=FALSE, warning=FALSE, messages=FALSE, results='hide'}
library(knitr)
library(ggplot2)
library(dplyr, warn.conflicts=FALSE)
library(lubridate, warn.conflicts=FALSE)

opts_chunk$set(fig.align='center', echo=FALSE)

pg_conf <- read.csv('rds_settings', stringsAsFactors=FALSE)
vs_db <- src_postgres(dbname='vitalsigns', host=pg_conf$host,
                      user=pg_conf$user, password=pg_conf$pass,
                      port=pg_conf$port)
```

Report generated `r now(tzone='UTC')` UTC.

## Number of household surveys by landscape


``` {r, fig.align="center"}
household <- tbl(vs_db, 'household')
hh_ls <- group_by(household, country, landscape_no) %>% 
    summarise(n()) %>%
    arrange(country, landscape_no) %>%
    collect() %>%
    print(n=50)
ggplot(hh_ls) +
    geom_bar(aes(factor(landscape_no), count, fill=country), stat='identity') +
    facet_grid(country ~ .) +
    xlab("Landscape") + ylab("Number of surveys")
```

## Number of household surveys by country

``` {r}
hh_country <- group_by(household, country) %>% 
    summarise(n()) %>%
    collect() %>%
    print()

ggplot(hh_country) +
    geom_bar(aes(factor(country), count, fill=country), stat='identity') +
    xlab("Country") + ylab("Number of surveys")
```

## Number of household surveys by date_of_interview

``` {r}
agric <- tbl(vs_db, 'agric')
agric_mth <- collect(agric) %>%
    group_by(year=year(date_of_interview),
             month=month(date_of_interview), 
             country, landscape_no) %>%
    summarise(count=n()) %>%
    arrange(country, landscape_no)

agric_mth$date <- with(agric_mth, as.Date(paste0(year, '/', month, '/15'), "%Y/%m/%d"))


ggplot(agric_mth) +
    geom_bar(aes(date, count, fill=landscape_no), stat='identity') +
    facet_grid(country ~ .) +
    scale_x_date(date_breaks='years', date_minor_breaks='months', date_labels='%Y') +
    xlab("Date") + ylab("Number of surveys")
```

## Number of household surveys with missing date_of_interview

By landscape:
``` {r}
agric_missing <- filter(agric_mth, is.na(year) | is.na(month)) %>%
    group_by(country, landscape_no) %>%
    select(-year, -month, -date) %>%
    print(n=100)
```

By country:
``` {r}
group_by(agric_missing, country) %>%
    summarise(count=sum(count))
```
