---
title: "Metadata Summary"
output:
    html_document
---

``` {r, include=FALSE}
library(knitr)
library(ggplot2)
library(dplyr, warn.conflicts=FALSE)
library(lubridate, warn.conflicts=FALSE)
library(reshape2)
library(DT)

opts_chunk$set(fig.align='center', echo=FALSE)

pg_conf <- read.csv('rds_settings', stringsAsFactors=FALSE)

vs_db <- src_postgres(dbname='vitalsigns', host=pg_conf$host,
                      user=pg_conf$user, password=pg_conf$pass,
                      port=pg_conf$port)

hh <- tbl(vs_db, 'household') %>%
        inner_join(tbl(vs_db, 'piigeo_household')) %>%
        group_by(country, landscape_no, eplot_no, hh_no, round) %>% 
        summarise(household=n()) %>%
        data.frame
ag <- tbl(vs_db, 'agric') %>%
        inner_join(tbl(vs_db, 'piigeo_agric')) %>%
        group_by(country, landscape_no, eplot_no, hh_no, round) %>% 
        summarise(agric=n()) %>%
        data.frame
hhv <- tbl(vs_db, 'householdcontact') %>%
        group_by(country, landscape_no, eplot_no, hh_no, round) %>% 
        summarise(household_secV=n()) %>%
        data.frame
ffs <- tbl(vs_db, 'farmsoils') %>%
        inner_join(tbl(vs_db, 'piigeo_farmsoils')) %>%
        group_by(country, landscape_no, eplot_no, hh_no, round) %>% 
        summarise(farmfieldsoils=n()) %>%
        data.frame
ffs_l <- tbl(vs_db, 'farmsoilslab') %>%
        inner_join(tbl(vs_db, 'piigeo_farmsoilslab')) %>%
        group_by(country, landscape_no, eplot_no, hh_no, round) %>% 
        summarise(farmfieldsoils_lab=n()) %>%
        data.frame
y_hh <- tbl(vs_db, 'yields') %>%
        inner_join(tbl(vs_db, 'piigeo_yields')) %>%
        group_by(country, landscape_no, eplot_no, hh_no, round) %>% 
        summarise(yields_hh=n()) %>%
        data.frame
y_l <- tbl(vs_db, 'yieldslab') %>%
        inner_join(tbl(vs_db, 'piigeo_yieldslab')) %>%
        group_by(country, landscape_no, eplot_no, hh_no, round) %>% 
        summarise(yieldslab_hh=n()) %>%
        data.frame
ffs_p <- tbl(vs_db, 'processedsoils_farm') %>%
        inner_join(tbl(vs_db, 'piigeo_processedsoils_farm')) %>%
        group_by(country, landscape_no, eplot_no, hh_no, round) %>% 
        summarise(farmfieldsoils_processed=n()) %>%
        data.frame

#Reduce(merge, c(hh, ag, hhv, ffs, ffs_l, ffs_ym, ffs_ypm, ffs_yw), all=T)

all <- Reduce(function(x,y) merge(x, y, all=T),
              list(hh, ag, ffs, hhv, ffs_l, y_hh, y_l, ffs_p)) %>%
          arrange(country, landscape_no, eplot_no, hh_no, round)

all[is.na(all)] <- 0
```

##A table of entries for households in the database across all of the household protocols, for targeting duplicates and missing records

Report generated `r now(tzone='UTC')` UTC.

```{r}
DT::datatable(all, rownames = F, colnames = c("C", "L", "E", "H", "R", "Household", "Agric", "FFS", "SecV", "FFS Lab", "Yields", "Yields Lab", "Processed Soils"))
```
