---
title: "Soils data collection Report"
output: 
    html_document:
        toc: true
---


``` {r, include=FALSE}
library(knitr)
library(ggplot2)
library(dplyr, warn.conflicts=FALSE)
library(lubridate, warn.conflicts=FALSE)
library(maps)
library(mapdata)

opts_chunk$set(fig.align='center', echo=FALSE)

pg_conf <- read.csv('rds_settings', stringsAsFactors=FALSE)
vs_db <- src_postgres(dbname='vitalsigns', host=pg_conf$host,
                      user=pg_conf$user, password=pg_conf$pass,
                      port=pg_conf$port)

ffs_soils <- tbl(vs_db, 'farmfieldsoils_processed') %>% data.frame
ffs_soils$type <- 'Farm Field Soils'

eplot_soils <- tbl(vs_db, 'eplotsoils_processed') %>% data.frame
eplot_soils$type <- 'Eplot Soils'

all_soils <- rbind(ffs_soils[ , c('country', 
                                  'landscape_no', 
                                  'eplot_no', 
                                  'type')], 
                   eplot_soils[ , c('country', 
                                    'landscape_no', 
                                    'eplot_no', 
                                    'type')])

eplot_coords <- tbl(vs_db, 'eplot') %>% data.frame

with_coords <- merge(all_soils, eplot_coords, all=F) %>% unique

```

Report generated `r now(tzone='UTC')` UTC.

## Number soil samples by country

``` {r, fig.align="center"}
soils_cty <- group_by(all_soils, country, type) %>%
    summarise(count=n()) %>%
    print(n=50)
ggplot(soils_cty) +
    geom_bar(aes(country, count, fill=type), stat='identity') +
    xlab("Country") + ylab("Number of Processed Samples")
```

## Number of soil samples by landscape

``` {r, fig.align="center"}
soils_l <- group_by(ffs_soils, country, landscape_no) %>%
    summarise(count=n()) %>%
    arrange(country, landscape_no) %>%
    collect() %>%
    print(n=50)
ggplot(soils_l) +
    geom_bar(aes(factor(landscape_no), count, fill=country), stat='identity') +
    facet_grid(country ~ .) +
    xlab("Landscape") + ylab("Number of Processed Samples")
```


## Map of soil samples in Uganda
``` {r, fig.align="center"}
map('worldHires', 'Uganda')
uga <- with_coords[ , c('country', "gpsse_lat", "gpsse_long")] %>% 
  filter(country=='UGA')
points(uga$gpsse_long, uga$gpsse_lat, col=2, pch=18)
```

## Map of soil samples in Ghana

``` {r, fig.align="center"}
map('worldHires', 'Ghana')
gha <- with_coords[ , c('country', "gpsse_lat", "gpsse_long")] %>% 
  filter(country=='GHA')
points(gha$gpsse_long, gha$gpsse_lat, col=2, pch=18)
```

## Map of soil samples in Tanzania

``` {r, fig.align="center"}
map('worldHires', 'Tanzania')
tza <- with_coords[ , c('country', "gpsse_lat", "gpsse_long")] %>% 
  filter(country=='TZA')
points(tza$gpsse_long, tza$gpsse_lat, col=2, pch=18)
```

## Map of soil samples in Rwanda

``` {r, fig.align="center"}
map('worldHires', 'Rwanda')
rwa <- with_coords[ , c('country', "gpsse_lat", "gpsse_long")] %>% 
  filter(country=='RWA')
points(rwa$gpsse_long, rwa$gpsse_lat, col=2, pch=18)
```
